TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.05
  max_rotation_vel: 1.0
  min_in_place_rotational_vel: 1.0
  backup_vel: -0.10

  acc_lim_th: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  holonomic_robot: false

  yaw_goal_tolerance: 6.28
  xy_goal_tolerance: 0.3

  path_distance_bias: 0.5
  goal_distance_bias: 0.5
  heading_lookahead: 0.1
  occdist_scale: 1.0

  dwa: true
  prune_plan: true
  controller_frequency: 2.0
  vtheta_samples: 30
  vx_samples: 3
  sim_granularity: 0.025
  sim_time: 6.0
