obstacle_range: 1.5
raytrace_range: 1.4
inflation_radius: 0.30
footprint: [[0.15,-0.20],[0.15,0.20],[-0.25,0.15],[-0.25,-0.15]]
transform_tolerance: 5.0
max_obstacle_height: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: wlaser
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
